name: Android CI

on: [push, pull_request, workflow_dispatch]

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Run tests and generate APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache packages
        id: cache-packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-packages-${{ runner.os }}-${{ hashFiles('**/*.gradle', '**/*.gradle.kts', 'gradle.properties') }}
          restore-keys: gradle-packages-${{ runner.os }}

      - name: Access test login credentials
        run: |
          echo "TEST_USER_NAME=${{ secrets.TEST_USER_NAME }}" >> local.properties
          echo "TEST_USER_PASSWORD=${{ secrets.TEST_USER_PASSWORD }}" >> local.properties



      - name: Run Unit tests with unified coverage
        if: github.event_name != 'pull_request'
        run: ./gradlew -Pcoverage testBetaDebugUnitTestUnifiedCoverage --stacktrace

      - name: Run Unit tests without unified coverage
        if: github.event_name == 'pull_request'
        run: ./gradlew -Pcoverage testBetaDebugUnitTestCoverage --stacktrace

      - name: Run Lint
        run: ./gradlew lintBetaDebug --stacktrace
        continue-on-error: true

      - name: Upload Lint Results
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: lint-results
          path: |
            app/build/reports/lint-results-betaDebug.xml
            app/build/reports/lint-results-betaDebug.html
        continue-on-error: true

      - name: Comment Lint Results on PR
        if: github.event_name == 'pull_request'
        uses: yutailang0119/action-android-lint@v4
        with:
          report-path: app/build/reports/lint-results-betaDebug.xml
        continue-on-error: true

      - name: Upload Test Report to Codecov
        if: github.event_name != 'pull_request'
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov -f "app/build/reports/jacoco/testBetaDebugUnitTestUnifiedCoverage/testBetaDebugUnitTestUnifiedCoverage.xml" -Z

      - name: Generate betaDebug APK
        run: bash ./gradlew assembleBetaDebug --stacktrace

      - name: Upload betaDebug APK
        uses: actions/upload-artifact@v4
        with:
          name: betaDebugAPK
          path: app/build/outputs/apk/beta/debug/app-*.apk

      - name: Generate prodDebug APK
        run: bash ./gradlew assembleProdDebug --stacktrace

      - name: Upload prodDebug APK
        uses: actions/upload-artifact@v4
        with:
          name: prodDebugAPK
          path: app/build/outputs/apk/prod/debug/app-*.apk

      - name: Create and PR number artifact
        run: |
          echo "{\"pr_number\": ${{ github.event.pull_request.number || 'null' }}}" > pr_number.json
          
      - name: Upload PR number artifact
        uses: actions/upload-artifact@v4
        with:
          name: pr_number
          path: ./pr_number.json
